"""Domain events, one module per bounded context. Re-exported here so
``from app.domain.events import X`` keeps working unchanged.
"""

from app.domain.events.base import DomainEvent
from app.domain.events.client import (
    ClientActivated,
    ClientDeactivated,
    ClientSuspended,
    ClientTerminated,
    ClientVerified,
)
from app.domain.events.clinical import (
    AuthorizationConsumed,
    AuthorizationExtended,
    AuthorizationExtensionRequested,
    AuthorizationGranted,
    CaseAdvanced,
    CaseAssigned,
    CaseClosed,
    CaseOpened,
    ClinicalNoteLocked,
    ClinicalNoteSigned,
    EAPProgrammeCreated,
)
from app.domain.events.consultancy import (
    EngagementActivated,
    EngagementClosed,
    EngagementCreated,
    EngagementDelivered,
    EngagementInvoiced,
    HoursLogged,
)
from app.domain.events.contract import ContractRenewed, ContractTerminated
from app.domain.events.crisis import (
    CaringContactCompleted,
    CaringContactScheduled,
    CrisisContactClosed,
    CrisisContactLogged,
    CrisisFlagRaised,
    CriticalIncidentClosed,
    CriticalIncidentLogged,
    CriticalIncidentPhaseRecorded,
    MandatoryReportSubmitted,
    RiskAssessmentRecorded,
    SafetyPlanActivated,
    SafetyPlanCreated,
    SafetyPlanReviewed,
    SafetyPlanSuperseded,
)
from app.domain.events.document import DocumentArchived, DocumentPublished, DocumentVersionCreated
from app.domain.events.manager import (
    FitnessForDutyRequested,
    FitnessForDutyResolved,
    ManagerConsultLogged,
    ManagerConsultReferralFiled,
    OutcomeMeasureRecorded,
    ReturnToWorkPlanActivated,
    ReturnToWorkPlanCompleted,
    TrainingEnrolmentCompleted,
    TrainingEnrolmentCreated,
    WorkLifeReferralRequested,
    WorkLifeReferralResolved,
)
from app.domain.events.outreach import (
    CareCallbackCampaignActivated,
    CareCallbackCampaignCompleted,
    CareCallbackCampaignCreated,
    OutreachAssigned,
    OutreachCompleted,
    SurveyCampaignActivated,
    SurveyCampaignClosed,
    SurveyCampaignCreated,
    SurveyResponseIngested,
)
from app.domain.events.person import (
    PersonActivated,
    PersonDeactivated,
    PersonSecondaryRoleAdded,
    PersonSecondaryRoleRemoved,
    PersonTerminated,
)
from app.domain.events.privacy import (
    ConsentExpired,
    ConsentGranted,
    ConsentRequested,
    ConsentRevoked,
    DataShareLogged,
    DSARErasureExecuted,
    DSARRequestCompleted,
    DSARRequestSubmitted,
)
from app.domain.events.provider import (
    ProviderAssignmentBlocked,
    ProviderPanelStatusChanged,
    ProviderTierChanged,
)
from app.domain.events.session import SessionCancelled, SessionCompleted, SessionRescheduled
from app.domain.events.tenancy import TenantActivated, TenantSuspended, TenantTerminated
from app.domain.events.user import (
    UserActivated,
    UserBanned,
    UserDeactivated,
    UserEmailVerified,
    UserLockedOut,
    UserLockoutCleared,
    UserLoginFailed,
    UserSuspended,
    UserTerminated,
)

__all__ = [
    "DomainEvent",
    "AuthorizationConsumed",
    "AuthorizationExtended",
    "AuthorizationExtensionRequested",
    "AuthorizationGranted",
    "CareCallbackCampaignActivated",
    "CareCallbackCampaignCompleted",
    "CareCallbackCampaignCreated",
    "CaringContactCompleted",
    "CaringContactScheduled",
    "CaseAdvanced",
    "CaseAssigned",
    "CaseClosed",
    "CaseOpened",
    "ClientActivated",
    "ClientDeactivated",
    "ClientSuspended",
    "ClientTerminated",
    "ClientVerified",
    "ClinicalNoteLocked",
    "ClinicalNoteSigned",
    "ConsentExpired",
    "ConsentGranted",
    "ConsentRequested",
    "ConsentRevoked",
    "ContractRenewed",
    "ContractTerminated",
    "CrisisContactClosed",
    "CrisisContactLogged",
    "CrisisFlagRaised",
    "CriticalIncidentClosed",
    "CriticalIncidentLogged",
    "CriticalIncidentPhaseRecorded",
    "DSARErasureExecuted",
    "DSARRequestCompleted",
    "DSARRequestSubmitted",
    "DataShareLogged",
    "DocumentArchived",
    "DocumentPublished",
    "DocumentVersionCreated",
    "EAPProgrammeCreated",
    "EngagementActivated",
    "EngagementClosed",
    "EngagementCreated",
    "EngagementDelivered",
    "EngagementInvoiced",
    "FitnessForDutyRequested",
    "FitnessForDutyResolved",
    "HoursLogged",
    "ManagerConsultLogged",
    "ManagerConsultReferralFiled",
    "MandatoryReportSubmitted",
    "OutcomeMeasureRecorded",
    "OutreachAssigned",
    "OutreachCompleted",
    "PersonActivated",
    "PersonDeactivated",
    "PersonSecondaryRoleAdded",
    "PersonSecondaryRoleRemoved",
    "PersonTerminated",
    "ProviderAssignmentBlocked",
    "ProviderPanelStatusChanged",
    "ProviderTierChanged",
    "ReturnToWorkPlanActivated",
    "ReturnToWorkPlanCompleted",
    "RiskAssessmentRecorded",
    "SafetyPlanActivated",
    "SafetyPlanCreated",
    "SafetyPlanReviewed",
    "SafetyPlanSuperseded",
    "SessionCancelled",
    "SessionCompleted",
    "SessionRescheduled",
    "SurveyCampaignActivated",
    "SurveyCampaignClosed",
    "SurveyCampaignCreated",
    "SurveyResponseIngested",
    "TenantActivated",
    "TenantSuspended",
    "TenantTerminated",
    "TrainingEnrolmentCompleted",
    "TrainingEnrolmentCreated",
    "UserActivated",
    "UserBanned",
    "UserDeactivated",
    "UserEmailVerified",
    "UserLockedOut",
    "UserLockoutCleared",
    "UserLoginFailed",
    "UserSuspended",
    "UserTerminated",
    "WorkLifeReferralRequested",
    "WorkLifeReferralResolved",
]
