"""add_missing_service_tables

Revision ID: 32b395f52e9f
Revises: 51a3ca5e6e38
Create Date: 2026-01-24 18:25:16.013430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '32b395f52e9f'
down_revision: Union[str, Sequence[str], None] = '51a3ca5e6e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def table_exists(table_name: str) -> bool:
    """Check if a table exists in the database."""
    conn = op.get_bind()
    inspector = inspect(conn)
    return table_name in inspector.get_table_names()


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not table_exists('audit_logs'):
        op.create_table('audit_logs',
    sa.Column('user_id', sa.String(length=25), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=25), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('tenant_id', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("action_type IN ('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'APPROVE', 'REJECT', 'LIST', 'VIEW', 'EXPORT', 'IMPORT')", name='audit_action_type_check'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('client_tags',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('tenant_id', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_tags_deleted_at'), 'client_tags', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_client_tags_is_active'), 'client_tags', ['is_active'], unique=False)
    op.create_index(op.f('ix_client_tags_name'), 'client_tags', ['name'], unique=False)
    op.create_index(op.f('ix_client_tags_tenant_id'), 'client_tags', ['tenant_id'], unique=False)
    op.create_table('industries',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('parent_industry_id', sa.String(length=25), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('tenant_id', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_industry_id'], ['industries.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industries_code'), 'industries', ['code'], unique=False)
    op.create_index(op.f('ix_industries_deleted_at'), 'industries', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_industries_is_active'), 'industries', ['is_active'], unique=False)
    op.create_index(op.f('ix_industries_name'), 'industries', ['name'], unique=False)
    op.create_index(op.f('ix_industries_parent_industry_id'), 'industries', ['parent_industry_id'], unique=False)
    op.create_index(op.f('ix_industries_tenant_id'), 'industries', ['tenant_id'], unique=False)
    op.create_table('kpis',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('measurement_unit', sa.String(), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('threshold_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('threshold_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('tenant_id', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("category IN ('Utilization', 'Satisfaction', 'Outcome', 'Operational')", name='kpi_category_check'),
    sa.CheckConstraint("measurement_unit IN ('Percentage', 'Count', 'Rate', 'Score', 'Time', 'Currency')", name='kpi_measurement_unit_check'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpis_category'), 'kpis', ['category'], unique=False)
    op.create_index(op.f('ix_kpis_deleted_at'), 'kpis', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_kpis_is_active'), 'kpis', ['is_active'], unique=False)
    op.create_index(op.f('ix_kpis_name'), 'kpis', ['name'], unique=False)
    op.create_index(op.f('ix_kpis_tenant_id'), 'kpis', ['tenant_id'], unique=False)
    op.create_table('services',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_group_service', sa.Boolean(), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('tenant_id', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('Active', 'Inactive', 'Pending', 'Archived', 'Deleted')", name='service_status_check'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_category'), 'services', ['category'], unique=False)
    op.create_index(op.f('ix_services_deleted_at'), 'services', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=False)
    op.create_index(op.f('ix_services_tenant_id'), 'services', ['tenant_id'], unique=False)
    op.create_table('activities',
    sa.Column('client_id', sa.String(length=25), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=25), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_follow_up', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_important', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('tenant_id', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_activity_type'), 'activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_activities_client_id'), 'activities', ['client_id'], unique=False)
    op.create_index(op.f('ix_activities_created_by'), 'activities', ['created_by'], unique=False)
    op.create_index(op.f('ix_activities_deleted_at'), 'activities', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_activities_is_important'), 'activities', ['is_important'], unique=False)
    op.create_index(op.f('ix_activities_next_follow_up'), 'activities', ['next_follow_up'], unique=False)
    op.create_index(op.f('ix_activities_occurred_at'), 'activities', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_activities_tenant_id'), 'activities', ['tenant_id'], unique=False)
    op.create_table('contacts',
    sa.Column('client_id', sa.String(length=25), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('tenant_id', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_client_id'), 'contacts', ['client_id'], unique=False)
    op.create_index(op.f('ix_contacts_deleted_at'), 'contacts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index(op.f('ix_contacts_is_active'), 'contacts', ['is_active'], unique=False)
    op.create_index(op.f('ix_contacts_is_primary'), 'contacts', ['is_primary'], unique=False)
    op.create_index(op.f('ix_contacts_name'), 'contacts', ['name'], unique=False)
    op.create_index(op.f('ix_contacts_tenant_id'), 'contacts', ['tenant_id'], unique=False)
    op.create_table('entity_changes',
    sa.Column('audit_log_id', sa.String(length=25), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=25), nullable=False),
    sa.Column('field_changes', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_log_id'], ['audit_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_changes_audit_log_id'), 'entity_changes', ['audit_log_id'], unique=False)
    op.create_index(op.f('ix_entity_changes_entity_id'), 'entity_changes', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_changes_entity_type'), 'entity_changes', ['entity_type'], unique=False)
    op.create_table('documents',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('previous_version_id', sa.String(length=25), nullable=True),
    sa.Column('uploaded_by', sa.String(length=25), nullable=True),
    sa.Column('client_id', sa.String(length=25), nullable=True),
    sa.Column('contract_id', sa.String(length=25), nullable=True),
    sa.Column('person_id', sa.String(length=25), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_confidential', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('tenant_id', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("document_type IN ('Contract', 'Certification', 'KPI Report', 'Feedback Summary', 'Billing Report', 'Utilization Report', 'Other')", name='document_type_check'),
    sa.CheckConstraint("status IN ('Draft', 'Published', 'Archived', 'Expired')", name='document_status_check'),
    sa.CheckConstraint('(file_path IS NOT NULL) OR (file_url IS NOT NULL)', name='document_file_or_url_check'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['previous_version_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_client_id'), 'documents', ['client_id'], unique=False)
    op.create_index(op.f('ix_documents_contract_id'), 'documents', ['contract_id'], unique=False)
    op.create_index(op.f('ix_documents_deleted_at'), 'documents', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_expires_at'), 'documents', ['expires_at'], unique=False)
    op.create_index(op.f('ix_documents_is_latest'), 'documents', ['is_latest'], unique=False)
    op.create_index(op.f('ix_documents_name'), 'documents', ['name'], unique=False)
    op.create_index(op.f('ix_documents_person_id'), 'documents', ['person_id'], unique=False)
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by'), 'documents', ['uploaded_by'], unique=False)
    op.create_table('kpi_assignments',
    sa.Column('kpi_id', sa.String(length=25), nullable=False),
    sa.Column('client_id', sa.String(length=25), nullable=True),
    sa.Column('contract_id', sa.String(length=25), nullable=True),
    sa.Column('target_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('tenant_id', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(client_id IS NOT NULL) OR (contract_id IS NOT NULL)', name='kpi_assignment_client_or_contract_check'),
    sa.CheckConstraint('(client_id IS NULL) OR (contract_id IS NULL)', name='kpi_assignment_not_both_check'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['kpi_id'], ['kpis.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_assignments_client_id'), 'kpi_assignments', ['client_id'], unique=False)
    op.create_index(op.f('ix_kpi_assignments_contract_id'), 'kpi_assignments', ['contract_id'], unique=False)
    op.create_index(op.f('ix_kpi_assignments_deleted_at'), 'kpi_assignments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_kpi_assignments_is_active'), 'kpi_assignments', ['is_active'], unique=False)
    op.create_index(op.f('ix_kpi_assignments_kpi_id'), 'kpi_assignments', ['kpi_id'], unique=False)
    op.create_index(op.f('ix_kpi_assignments_tenant_id'), 'kpi_assignments', ['tenant_id'], unique=False)
    op.create_table('service_assignments',
    sa.Column('service_id', sa.String(length=25), nullable=False),
    sa.Column('contract_id', sa.String(length=25), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_by', sa.String(length=25), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('tenant_id', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_assignments_contract_id'), 'service_assignments', ['contract_id'], unique=False)
    op.create_index(op.f('ix_service_assignments_deleted_at'), 'service_assignments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_service_assignments_service_id'), 'service_assignments', ['service_id'], unique=False)
    op.create_index(op.f('ix_service_assignments_tenant_id'), 'service_assignments', ['tenant_id'], unique=False)
    op.create_table('service_sessions',
    sa.Column('service_id', sa.String(length=25), nullable=False),
    sa.Column('provider_id', sa.String(length=25), nullable=False),
    sa.Column('person_id', sa.String(length=25), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reschedule_count', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('feedback', sa.String(length=2000), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=25), nullable=False),
    sa.Column('tenant_id', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('Scheduled', 'Rescheduled', 'Completed', 'Cancelled', 'No Show')", name='session_status_check'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_sessions_deleted_at'), 'service_sessions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_service_sessions_person_id'), 'service_sessions', ['person_id'], unique=False)
    op.create_index(op.f('ix_service_sessions_provider_id'), 'service_sessions', ['provider_id'], unique=False)
    op.create_index(op.f('ix_service_sessions_scheduled_at'), 'service_sessions', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_service_sessions_service_id'), 'service_sessions', ['service_id'], unique=False)
    op.create_index(op.f('ix_service_sessions_tenant_id'), 'service_sessions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_sessions_tenant_id'), table_name='service_sessions')
    op.drop_index(op.f('ix_service_sessions_service_id'), table_name='service_sessions')
    op.drop_index(op.f('ix_service_sessions_scheduled_at'), table_name='service_sessions')
    op.drop_index(op.f('ix_service_sessions_provider_id'), table_name='service_sessions')
    op.drop_index(op.f('ix_service_sessions_person_id'), table_name='service_sessions')
    op.drop_index(op.f('ix_service_sessions_deleted_at'), table_name='service_sessions')
    op.drop_table('service_sessions')
    op.drop_index(op.f('ix_service_assignments_tenant_id'), table_name='service_assignments')
    op.drop_index(op.f('ix_service_assignments_service_id'), table_name='service_assignments')
    op.drop_index(op.f('ix_service_assignments_deleted_at'), table_name='service_assignments')
    op.drop_index(op.f('ix_service_assignments_contract_id'), table_name='service_assignments')
    op.drop_table('service_assignments')
    op.drop_index(op.f('ix_kpi_assignments_tenant_id'), table_name='kpi_assignments')
    op.drop_index(op.f('ix_kpi_assignments_kpi_id'), table_name='kpi_assignments')
    op.drop_index(op.f('ix_kpi_assignments_is_active'), table_name='kpi_assignments')
    op.drop_index(op.f('ix_kpi_assignments_deleted_at'), table_name='kpi_assignments')
    op.drop_index(op.f('ix_kpi_assignments_contract_id'), table_name='kpi_assignments')
    op.drop_index(op.f('ix_kpi_assignments_client_id'), table_name='kpi_assignments')
    op.drop_table('kpi_assignments')
    op.drop_index(op.f('ix_documents_uploaded_by'), table_name='documents')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_person_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_name'), table_name='documents')
    op.drop_index(op.f('ix_documents_is_latest'), table_name='documents')
    op.drop_index(op.f('ix_documents_expires_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_deleted_at'), table_name='documents')
    op.drop_index(op.f('ix_documents_contract_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_client_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_entity_changes_entity_type'), table_name='entity_changes')
    op.drop_index(op.f('ix_entity_changes_entity_id'), table_name='entity_changes')
    op.drop_index(op.f('ix_entity_changes_audit_log_id'), table_name='entity_changes')
    op.drop_table('entity_changes')
    op.drop_index(op.f('ix_contacts_tenant_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_is_primary'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_is_active'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_deleted_at'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_client_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_activities_tenant_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_occurred_at'), table_name='activities')
    op.drop_index(op.f('ix_activities_next_follow_up'), table_name='activities')
    op.drop_index(op.f('ix_activities_is_important'), table_name='activities')
    op.drop_index(op.f('ix_activities_deleted_at'), table_name='activities')
    op.drop_index(op.f('ix_activities_created_by'), table_name='activities')
    op.drop_index(op.f('ix_activities_client_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_activity_type'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_services_tenant_id'), table_name='services')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_index(op.f('ix_services_deleted_at'), table_name='services')
    op.drop_index(op.f('ix_services_category'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_kpis_tenant_id'), table_name='kpis')
    op.drop_index(op.f('ix_kpis_name'), table_name='kpis')
    op.drop_index(op.f('ix_kpis_is_active'), table_name='kpis')
    op.drop_index(op.f('ix_kpis_deleted_at'), table_name='kpis')
    op.drop_index(op.f('ix_kpis_category'), table_name='kpis')
    op.drop_table('kpis')
    op.drop_index(op.f('ix_industries_tenant_id'), table_name='industries')
    op.drop_index(op.f('ix_industries_parent_industry_id'), table_name='industries')
    op.drop_index(op.f('ix_industries_name'), table_name='industries')
    op.drop_index(op.f('ix_industries_is_active'), table_name='industries')
    op.drop_index(op.f('ix_industries_deleted_at'), table_name='industries')
    op.drop_index(op.f('ix_industries_code'), table_name='industries')
    op.drop_table('industries')
    op.drop_index(op.f('ix_client_tags_tenant_id'), table_name='client_tags')
    op.drop_index(op.f('ix_client_tags_name'), table_name='client_tags')
    op.drop_index(op.f('ix_client_tags_is_active'), table_name='client_tags')
    op.drop_index(op.f('ix_client_tags_deleted_at'), table_name='client_tags')
    op.drop_table('client_tags')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
