"""Backwards-compatible re-export.

These value objects moved into per-domain modules alongside this one
(ids, identity, money, dates, tenancy, contact, staffing). This module
keeps ``from app.domain.value_objects.core import X`` working for the
257 existing call sites; new code should import from the specific module.
"""

from app.domain.value_objects.contact import Address, ContactInfo, EmergencyContact
from app.domain.value_objects.dates import DateRange
from app.domain.value_objects.identity import Email, TenantCode
from app.domain.value_objects.ids import (
    ActivityId,
    AuditLogId,
    AuthorizationId,
    BenchmarkConsentId,
    CareCallbackCampaignId,
    CaringContactId,
    CaseId,
    ClientId,
    ClientTagId,
    ClinicalNoteId,
    ClinicalSubjectId,
    ConsentId,
    ContactId,
    ContractId,
    CrisisContactId,
    CriticalIncidentId,
    DataSharingRegisterEntryId,
    DeliverableId,
    DocumentId,
    DPOContactId,
    DSARRequestId,
    EAPProgrammeId,
    EligibleMemberId,
    EngagementId,
    EntityChangeId,
    FitnessForDutyId,
    HoursLogEntryId,
    Id,
    IndustryId,
    KPIAssignmentId,
    KPIId,
    ManagerConsultId,
    MandatoryReportId,
    NonCompeteClauseId,
    NoteAmendmentId,
    OutcomeMeasureId,
    OutreachRecordId,
    PersonId,
    ReportRunId,
    ReportTemplateId,
    ReturnToWorkPlanId,
    RiskAssessmentId,
    SafetyPlanId,
    ServiceAssignmentId,
    ServiceId,
    SessionId,
    SurveyCampaignId,
    SurveyResponseId,
    TenantId,
    TrainingEnrolmentId,
    TriageResponseId,
    UserId,
    UtilisationEventId,
    WorkLifeProviderId,
    WorkLifeReferralId,
)
from app.domain.value_objects.money import Money
from app.domain.value_objects.staffing import (
    ClientEmployeeCode,
    DependentInfo,
    EmploymentInfo,
    LicenseInfo,
    ProviderProfile,
    StaffInfo,
)
from app.domain.value_objects.tenancy import TenantSettings

__all__ = [
    "ActivityId",
    "AuditLogId",
    "AuthorizationId",
    "BenchmarkConsentId",
    "CareCallbackCampaignId",
    "CaringContactId",
    "CaseId",
    "ClientId",
    "ClientTagId",
    "ClinicalNoteId",
    "ClinicalSubjectId",
    "ConsentId",
    "ContactId",
    "ContractId",
    "CrisisContactId",
    "CriticalIncidentId",
    "DPOContactId",
    "DSARRequestId",
    "DataSharingRegisterEntryId",
    "DeliverableId",
    "DocumentId",
    "EAPProgrammeId",
    "EligibleMemberId",
    "EngagementId",
    "EntityChangeId",
    "FitnessForDutyId",
    "HoursLogEntryId",
    "Id",
    "IndustryId",
    "KPIAssignmentId",
    "KPIId",
    "ManagerConsultId",
    "MandatoryReportId",
    "NonCompeteClauseId",
    "NoteAmendmentId",
    "OutcomeMeasureId",
    "OutreachRecordId",
    "PersonId",
    "ReportRunId",
    "ReportTemplateId",
    "ReturnToWorkPlanId",
    "RiskAssessmentId",
    "SafetyPlanId",
    "ServiceAssignmentId",
    "ServiceId",
    "SessionId",
    "SurveyCampaignId",
    "SurveyResponseId",
    "TenantId",
    "TrainingEnrolmentId",
    "TriageResponseId",
    "UserId",
    "UtilisationEventId",
    "WorkLifeProviderId",
    "WorkLifeReferralId",
    "Email",
    "TenantCode",
    "Money",
    "DateRange",
    "TenantSettings",
    "Address",
    "ContactInfo",
    "EmergencyContact",
    "ClientEmployeeCode",
    "DependentInfo",
    "EmploymentInfo",
    "LicenseInfo",
    "ProviderProfile",
    "StaffInfo",
]
