"""Initial migration

Revision ID: 4bff82b20fb3
Revises: 
Create Date: 2026-01-22 14:37:25.168528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bff82b20fb3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Suspended', 'Terminated', 'Archived', name='tenantstatus'), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('subscription_tier', sa.Enum('Free', 'Basic', 'Professional', 'Enterprise', name='subscriptiontier'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('Active', 'Suspended', 'Terminated', 'Archived')", name='tenant_status_check'),
    sa.CheckConstraint("subscription_tier IN ('Free', 'Basic', 'Professional', 'Enterprise')", name='tenant_subscription_tier_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_code'), 'tenants', ['code'], unique=True)
    op.create_index(op.f('ix_tenants_deleted_at'), 'tenants', ['deleted_at'], unique=False)
    op.create_table('clients',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_info', sa.JSON(), nullable=False),
    sa.Column('billing_address', sa.JSON(), nullable=True),
    sa.Column('industry_id', sa.String(length=25), nullable=True),
    sa.Column('parent_client_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Pending', 'Archived', 'Deleted', name='basestatus'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('preferred_contact_method', sa.Enum('email', 'phone', 'sms', 'whatsapp', 'wechat', name='contactmethod'), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("preferred_contact_method IN ('email', 'phone', 'sms', 'whatsapp', 'wechat')", name='client_contact_method_check'),
    sa.CheckConstraint("status IN ('Active', 'Inactive', 'Pending', 'Archived', 'Deleted')", name='client_status_check'),
    sa.ForeignKeyConstraint(['parent_client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_deleted_at'), 'clients', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_clients_industry_id'), 'clients', ['industry_id'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_index(op.f('ix_clients_parent_client_id'), 'clients', ['parent_client_id'], unique=False)
    op.create_index(op.f('ix_clients_tenant_id'), 'clients', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Suspended', 'Banned', 'Terminated', 'Pending Verification', 'Inactive', name='userstatus'), nullable=False),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferred_language', sa.Enum('en', 'es', 'fr', 'de', 'it', 'pt', 'zh', 'ja', 'ko', name='language'), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('is_two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("preferred_language IN ('en', 'es', 'fr', 'de', 'it', 'pt', 'zh', 'ja', 'ko')", name='user_language_check'),
    sa.CheckConstraint("status IN ('Active', 'Suspended', 'Banned', 'Terminated', 'Pending Verification', 'Inactive')", name='user_status_check'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('contracts',
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('period', sa.JSON(), nullable=False),
    sa.Column('billing_rate', sa.JSON(), nullable=False),
    sa.Column('payment_frequency', sa.Enum('Weekly', 'Monthly', 'Quarterly', 'Annually', name='paymentfrequency'), nullable=False),
    sa.Column('payment_status', sa.Enum('Pending', 'Paid', 'Overdue', 'Cancelled', 'Refunded', name='paymentstatus'), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Expired', 'Terminated', 'Renewed', 'Pending', 'Draft', name='contractstatus'), nullable=False),
    sa.Column('is_auto_renew', sa.Boolean(), nullable=False),
    sa.Column('last_billing_date', sa.Date(), nullable=True),
    sa.Column('next_billing_date', sa.Date(), nullable=True),
    sa.Column('signed_by', sa.String(length=255), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('termination_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("payment_frequency IN ('Weekly', 'Monthly', 'Quarterly', 'Annually')", name='contract_payment_frequency_check'),
    sa.CheckConstraint("payment_status IN ('Pending', 'Paid', 'Overdue', 'Cancelled', 'Refunded')", name='contract_payment_status_check'),
    sa.CheckConstraint("status IN ('Active', 'Expired', 'Terminated', 'Renewed', 'Pending', 'Draft')", name='contract_status_check'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_client_id'), 'contracts', ['client_id'], unique=False)
    op.create_index(op.f('ix_contracts_deleted_at'), 'contracts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_contracts_tenant_id'), 'contracts', ['tenant_id'], unique=False)
    op.create_table('persons',
    sa.Column('person_type', sa.Enum('PlatformStaff', 'ClientEmployee', 'Dependent', 'ServiceProvider', name='persontype'), nullable=False),
    sa.Column('is_dual_role', sa.Boolean(), nullable=False),
    sa.Column('secondary_person_type', sa.Enum('PlatformStaff', 'ClientEmployee', 'Dependent', 'ServiceProvider', name='persontype'), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('employment_info', sa.JSON(), nullable=True),
    sa.Column('license_info', sa.JSON(), nullable=True),
    sa.Column('staff_info', sa.JSON(), nullable=True),
    sa.Column('dependent_info', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Pending', 'Archived', 'Deleted', name='basestatus'), nullable=False),
    sa.Column('emergency_contact', sa.JSON(), nullable=True),
    sa.Column('last_service_date', sa.Date(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("person_type IN ('PlatformStaff', 'ClientEmployee', 'Dependent', 'ServiceProvider')", name='person_type_check'),
    sa.CheckConstraint("secondary_person_type IN ('PlatformStaff', 'ClientEmployee', 'Dependent', 'ServiceProvider')", name='person_secondary_type_check'),
    sa.CheckConstraint("status IN ('Active', 'Inactive', 'Pending', 'Archived', 'Deleted')", name='person_status_check'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_deleted_at'), 'persons', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_persons_tenant_id'), 'persons', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_persons_user_id'), 'persons', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_persons_user_id'), table_name='persons')
    op.drop_index(op.f('ix_persons_tenant_id'), table_name='persons')
    op.drop_index(op.f('ix_persons_deleted_at'), table_name='persons')
    op.drop_table('persons')
    op.drop_index(op.f('ix_contracts_tenant_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_deleted_at'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_client_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_clients_tenant_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_parent_client_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_industry_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_deleted_at'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_tenants_deleted_at'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_code'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
