"""Use EnumValueType to store enum values instead of names

Revision ID: 748f01f4ddf3
Revises: 943f1a443954
Create Date: 2026-01-22 14:45:33.084329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '748f01f4ddf3'
down_revision: Union[str, Sequence[str], None] = '943f1a443954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
