"""Domain enums, one module per bounded context. Re-exported here so
``from app.domain.enums import X`` keeps working unchanged.
"""

from app.domain.enums.clinical import (
    AuthorizationStatus,
    CaseClosureReason,
    CaseReferralSource,
    CaseStatus,
    ClientTier,
    ClinicalNoteType,
    PresentingProblem,
    StageOfChange,
    TriageInstrumentCode,
    TriageRiskLevel,
)
from app.domain.enums.consultancy import DeliverableStatus, EngagementStatus
from app.domain.enums.contract import (
    BenchmarkScope,
    ContractStatus,
    PaymentFrequency,
    PaymentStatus,
    PricingModel,
)
from app.domain.enums.crisis import (
    CrisisCallerRelation,
    CrisisContactOutcome,
    CrisisWarmHandoff,
    CriticalIncidentPhase,
    CriticalIncidentSeverity,
    CriticalIncidentStatus,
    MandatoryReportType,
    SafetyPlanStatus,
)
from app.domain.enums.documents import DocumentStatus, DocumentType
from app.domain.enums.manager import (
    FitnessForDutyOutcome,
    ManagerConsultTopic,
    ReturnToWorkPlanStatus,
    TrainingEnrolmentStatus,
    WorkLifeReferralOutcome,
    WorkLifeServiceType,
)
from app.domain.enums.outreach import (
    CareCallbackCampaignStatus,
    CaringContactChannel,
    CaringContactOutcome,
    OutreachStatus,
    SurveyCampaignStatus,
    SurveySource,
    UtilisationEventType,
)
from app.domain.enums.person import (
    AuthProvider,
    ContactMethod,
    EligibilityStatus,
    Language,
    MemberRelation,
    PersonType,
    RelationType,
    StaffRole,
    UserStatus,
    WorkStatus,
)
from app.domain.enums.privacy import (
    ConsentPurpose,
    ConsentScope,
    ConsentStatus,
    DSARRequestStatus,
    DSARRequestType,
    RetentionDataClass,
)
from app.domain.enums.provider import (
    AccreditationStatus,
    NonCompeteStatus,
    PanelStatus,
    ProviderTier,
    UgandaRegion,
)
from app.domain.enums.reporting import (
    AuditActionType,
    KPICategory,
    KPIMeasurementUnit,
    ReportQueryType,
    ReportRunStatus,
)
from app.domain.enums.session import (
    BaseStatus,
    ClientType,
    ServiceCategory,
    SessionCategory,
    SessionClinicalStatus,
    SessionStatus,
    SessionType,
)
from app.domain.enums.tenancy import (
    AccessScope,
    SubscriptionTier,
    TenantConsentStatus,
    TenantRole,
    TenantStatus,
)

__all__ = [
    "AccessScope",
    "AccreditationStatus",
    "AuditActionType",
    "AuthProvider",
    "AuthorizationStatus",
    "BaseStatus",
    "BenchmarkScope",
    "CareCallbackCampaignStatus",
    "CaringContactChannel",
    "CaringContactOutcome",
    "CaseClosureReason",
    "CaseReferralSource",
    "CaseStatus",
    "ClientTier",
    "ClientType",
    "ClinicalNoteType",
    "ConsentPurpose",
    "ConsentScope",
    "ConsentStatus",
    "ContactMethod",
    "ContractStatus",
    "CrisisCallerRelation",
    "CrisisContactOutcome",
    "CrisisWarmHandoff",
    "CriticalIncidentPhase",
    "CriticalIncidentSeverity",
    "CriticalIncidentStatus",
    "DSARRequestStatus",
    "DSARRequestType",
    "DeliverableStatus",
    "DocumentStatus",
    "DocumentType",
    "EligibilityStatus",
    "EngagementStatus",
    "FitnessForDutyOutcome",
    "KPICategory",
    "KPIMeasurementUnit",
    "Language",
    "ManagerConsultTopic",
    "MandatoryReportType",
    "MemberRelation",
    "NonCompeteStatus",
    "OutreachStatus",
    "PanelStatus",
    "PaymentFrequency",
    "PaymentStatus",
    "PersonType",
    "PresentingProblem",
    "PricingModel",
    "ProviderTier",
    "RelationType",
    "ReportQueryType",
    "ReportRunStatus",
    "RetentionDataClass",
    "ReturnToWorkPlanStatus",
    "SafetyPlanStatus",
    "ServiceCategory",
    "SessionCategory",
    "SessionClinicalStatus",
    "SessionStatus",
    "SessionType",
    "StaffRole",
    "StageOfChange",
    "SubscriptionTier",
    "SurveyCampaignStatus",
    "SurveySource",
    "TenantConsentStatus",
    "TenantRole",
    "TenantStatus",
    "TrainingEnrolmentStatus",
    "TriageInstrumentCode",
    "TriageRiskLevel",
    "UgandaRegion",
    "UserStatus",
    "UtilisationEventType",
    "WorkLifeReferralOutcome",
    "WorkLifeServiceType",
    "WorkStatus",
]
